# Generated by Django 5.1.6 on 2025-04-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='backend.event'),
        ),
    ]
