services:
  db:
    image: postgres
    container_name: clubhub_db
    restart: always
    environment:
      POSTGRES_DB: clubhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=clubhub
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["npm", "start"]

volumes:
  postgres_data:

  # Uncomment to enable production with Nginx
  # frontend-prod:
  #   build:
  #     context: ./frontend
  #     target: production  # Use the "production" stage from Dockerfile
  #   ports:
  #     - "80:80"
