version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend
      target: development  # Use the "development" stage from Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      # - /app/node_modules  # Commented out to avoid potential issues
    stdin_open: true
    tty: true
    command: ["npm", "start"]  # Make sure that its running the dev server

  # Uncomment to enable production with Nginx
  # frontend-prod:
  #   build:
  #     context: ./frontend
  #     target: production  # Use the "production" stage from Dockerfile
  #   ports:
  #     - "80:80"
